services:
  postgres:
    image: postgres:15.8
    container_name: exam-postgres
    environment:
      POSTGRES_DB: examdb
      POSTGRES_USER: exam
      POSTGRES_PASSWORD: exam
    ports:
      - "5432:5432"
    volumes:
      - exam_pgdata:/var/lib/postgresql/data

volumes:
  exam_pgdata:
