version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: exam-postgres
    environment:
      POSTGRES_DB: examdb
      POSTGRES_USER: exam
      POSTGRES_PASSWORD: exam
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  exam-api:
    build: .
    container_name: exam-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/examdb
      SPRING_DATASOURCE_USERNAME: exam
      SPRING_DATASOURCE_PASSWORD: exam
    restart: unless-stopped

volumes:
  postgres_data:
