spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/examdb
    username: exam
    password: exam
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/exam

server:
  port: 8080
