spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/examdb
    username: ${DB_USERNAME:exam}
    password: ${DB_PASSWORD:exam}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/exam

springdoc:
  swagger-ui:
    path: /swagger-ui.html

keycloak:
  admin:
    server-url: http://localhost:8081
    realm: exam
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}

logging:
  level:
    org.flywaydb: DEBUG
    org.springdoc: DEBUG
    io.swagger.v3: DEBUG
    org.keycloak: DEBUG

